### ISSUE TITLE
Fix wording in README

### ISSUE THREAD

**Issue by dune73** [coreruleset/fake-bot-plugin#2]
## Testing

After configuration, **antivirus** protection should be tested, for example, using:
curl http://localhost --header "User-Agent: Googlebot"

It would also be useful if you would indicate the expected behaviour and log entry.

**Comment by azurit** [comment]
Thanks, should be fixed, pls check it.

**Comment by dune73** [comment]
Looks good. And thanks for the error message. Rule ID is wrong, though. And please check message too.

**Comment by azurit** [comment]
Fixed.

**Comment by dune73** [comment]
Thank you.
