### ISSUE TITLE
Use "Impersonator"

### ISSUE THREAD

**Issue by theMiddleBlue** [coreruleset/fake-bot-plugin#4]
really useful plugin @azurit !

Is it possible to use "Impersonator" instead of "fake bot"? According to other vendors, "Impersonator" should be the right category name of this kind of "bad bots".

**Comment by azurit** [comment]
Sure, could be Impersonator plugin. Is it possible to rename a repository?

**Comment by dune73** [comment]
While technically correct, the term impersonator implies a person, while it's clearly a bot / agent and the term "fake" points in the direction of impersonation too. I'd suggest to use impersonator in the description on the README.

**Comment by dune73** [comment]
Implementing this proposal in https://github.com/coreruleset/fake-bot-plugin/pull/5

**Comment by azurit** [comment]
@theMiddleBlue Are you happy with this solution?

**Comment by theMiddleBlue** [comment]
LGTM thanks!

**Comment by azurit** [comment]
Thanks, closing!
