### ISSUE TITLE
Support for Twitterbot.

### ISSUE THREAD

**Issue by dune73** [coreruleset/fake-bot-plugin#7]
I saw the following UA faking twitterbot:

`twitterbot/1.0`

Do not know if a real twitterbot is scanning the net.

**Comment by azurit** [comment]
Try it now:
https://github.com/coreruleset/fake-bot-plugin/commit/0a0aa2b888555ee5061bf9db92e0d7f6c3fe5b0e

**Comment by dune73** [comment]
Awesome. Thank you very much.
